pipeline:
  install:
    image: mhart/alpine-node:10.15
    commands:
      - node -v
      - npm -v
      - npm install
      - npm install -g mocha
      - mocha test/api.js
    when:
      branch: master
      event: tag

  build_image:
    image: plugins/ecr
    privileged: true
    repo: 147369302622.dkr.ecr.ap-northeast-1.amazonaws.com/drone-demo
    registry: 147369302622.dkr.ecr.ap-northeast-1.amazonaws.com
    region: ap-northeast-1
    environment:
      - DOCKER_LAUNCH_DEBUG=false
    debug: false
    tags:
      - latest
      - ${DRONE_COMMIT}
      - ${DRONE_TAG}
    dockerfile: Dockerfile
    secrets: [ ecr_access_key, ecr_secret_key ]
    when:
      branch: master
      event: tag

  scp:
    image: appleboy/drone-scp
    port: 22
    secrets:
      - source: host
        target: scp_host
      - source: user_name
        target: scp_username
      - source: key_path
        target: scp_key_path
    volumes:
      - /Users/mobilegomaji/.ssh:/ssh
    rm: true
    target: /home/ec2-user/drone-demo/
    source: 
      - docker-compose.yml
    when:
      branch: master
      event: tag

  restart_docker:
    image: appleboy/drone-ssh
    secrets:
      - source: host
        target: ssh_host
      - source: user_name
        target: ssh_username
      - source: key_path
        target: ssh_key_path
    volumes:
      - /Users/mobilegomaji/.ssh:/ssh
    script:
      - sleep 30
      - cd /home/ec2-user/drone-demo/
      - echo "run docker"
      - docker-compose stop
      - docker-compose pull
      - docker-compose up -d --force-recreate --build
      - exit 0
    when:
      branch: master
      event: tag

  notify:
    image: plugins/slack
    channel: gomaji_shell
    secrets: [ slack_webhook ]
    username: Drone CI
    when:
      status: [ success, failure ]
      branch: master
      event: tag
